# https://taskfile.dev/#/
version: "3"

tasks:
  lint:
    cmds:
      - black --check .
      - isort --check .
      - flake8
      - mypy
  format:
    cmds:
      - black .
      - isort .
  test:
    cmds:
      - pylint src tests
